version: '3.8'

# This file defines the services for the DEVELOPMENT environment.
# Services are isolated by the 'dev_network'.
# Service discovery is handled by Docker DNS (e.g., http://email-service:3000).

networks:
  dev_network:
    driver: bridge
    name: dev_network

services:
  # --- Service Definitions ---
  email-service:
    image: ghcr.io/orangeqtym/email-service:dev
    restart: always
    networks:
      - dev_network
    env_file:
      - .env.dev
    ports:
      - "6001:3000" # Mapped to 6001 to avoid local conflicts

  meal-planner-api:
    image: ghcr.io/orangeqtym/meal-planner-api:dev
    restart: always
    networks:
      - dev_network
    ports:
      - "3001:3001" # Mapped to 3001

  database:
    image: postgres:15
    restart: always
    networks:
      - dev_network
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: system_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  api-service:
    image: nginx:alpine
    restart: always
    networks:
      - dev_network
    ports:
      - "6003:80"
    depends_on:
      - database

  webapp:
    image: nginx:alpine
    restart: always
    networks:
      - dev_network
    ports:
      - "6004:80"

volumes:
  db_data:
