version: '3.8'

# This file defines the services for the DEVELOPMENT environment.
# Services are isolated by the 'dev_network'.
# Service discovery is handled by Docker DNS (e.g., http://email-service:3000).

networks:
  dev_network:
    driver: bridge
    name: dev_network

services:
  # --- Service Definitions ---
  email-service:
    image: ghcr.io/orangeqtym/email-service:dev
    restart: always
    networks:
      - dev_network
    env_file:
      - .env.dev
    ports:
      - "6001:3000" # Mapped to 6001 to avoid local conflicts

  meal-planner-api:
    image: ghcr.io/orangeqtym/meal-planner-api:dev
    restart: always
    networks:
      - dev_network
    ports:
      - "3001:3001" # Mapped to 3001
