version: '3.8'

# This file defines the services for the PRODUCTION environment.
# Services are isolated by the 'prod_network'.
# Service discovery is handled by Docker DNS (e.g., http://email-service:3000).

networks:
  prod_network:
    driver: bridge
    name: prod_network

services:
  # --- Service Definitions ---
  email-service:
    image: ghcr.io/orangeqtym/email-service:v1.0.0 # This tag will be updated by your release process
    restart: always
    networks:
      - prod_network
    env_file:
      - .env.prod
    ports:
      - "5000:3000" # Prod environment uses 5xxx ports

  meal-planner-api:
    image: ghcr.io/orangeqtym/meal-planner-api:latest
    restart: always
    networks:
      - prod_network
    env_file:
      - .env.prod
    environment:
      # Database Configuration
      DB_HOST: ${MEAL_PLANNER_DB_HOST}
      DB_PORT: ${MEAL_PLANNER_DB_PORT}
      DB_NAME: ${MEAL_PLANNER_DB_NAME}
      DB_USER: ${MEAL_PLANNER_DB_USER}
      DB_PASSWORD: ${MEAL_PLANNER_DB_PASSWORD}

      # API Configuration
      PORT: ${MEAL_PLANNER_PORT}
      NODE_ENV: production
      CORS_ORIGIN: ${MEAL_PLANNER_CORS_ORIGIN}
      LOG_LEVEL: ${MEAL_PLANNER_LOG_LEVEL}
    ports:
      - "5001:3001"
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  database:
    image: postgres:15
    restart: always
    networks:
      - prod_network
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: system_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  api-service:
    image: nginx:alpine
    restart: always
    networks:
      - prod_network
    ports:
      - "5003:80"
    depends_on:
      - database

  webapp:
    image: nginx:alpine
    restart: always
    networks:
      - prod_network
    ports:
      - "5004:80"

volumes:
  db_data:
