version: '3.8'

# This file defines the services for the PRODUCTION environment.
# Services are isolated by the 'prod_network'.
# Service discovery is handled by Docker DNS (e.g., http://email-service:3000).

networks:
  prod_network:
    driver: bridge
    name: prod_network

services:
  # --- Service Definitions ---
  email-service:
    image: ghcr.io/orangeqtym/email-service:v1.0.0 # This tag will be updated by your release process
    restart: always
    networks:
      - prod_network
    env_file:
      - .env.prod

  database:
    image: postgres:15
    restart: always
    networks:
      - prod_network
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: system_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  api-service:
    image: nginx:alpine
    restart: always
    networks:
      - prod_network
    ports:
      - "6103:80"
    depends_on:
      - database

  webapp:
    image: nginx:alpine
    restart: always
    networks:
      - prod_network
    ports:
      - "6104:80"

volumes:
  db_data:
